on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
      - main
  pull_request:
      types: [opened, synchronize, reopened]

name: SonarQube Scan

jobs:
  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Define your secret in GitHub repository settings
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
#        with:
#          java-version: 1

      - name: Run SonarScanner
        run: |
          # Download and install SonarScanner if needed
          if [ ! -f sonar-scanner.zip ]; then
            curl -o sonar-scanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-x.y.z.zip # Replace with the desired version
            unzip sonar-scanner.zip
          fi

          # Run SonarScanner analysis
          ./sonar-scanner \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.host.url=$SONAR_HOST_URL
